name: Hiven Ou
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Gopher, Javaer, Pythoner, Rustcer, Full Stack Engineer.'
company: Daocloud # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: China # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: ouguiyong@gmail.com
  github: HeavenTonight
  twitter: Hiven_Ou
  patreon: hiven
  paypal: hiven
  rss: "" # Remove RSS
